'use strict';
const test = require('node:test'); const assert = require('node:assert/strict'); const http = require('node:http'); const express = require('express'); const Database = require('better-sqlite3');
const { ensureCoreSchema } = require('../db/coreSchema'); const { requireAnyRole } = require('../permissions'); const allocation = require('../services/materialAllocationPlanningV2'); const createRouter = require('../routes/materialConsumption');
function request(port, method, path, role, body) { return new Promise((resolve, reject) => { const payload = body && JSON.stringify(body); const req = http.request({ port, method, path, headers: { 'x-role': role, 'content-type': 'application/json', ...(payload ? { 'content-length': Buffer.byteLength(payload) } : {}) } }, res => { let data=''; res.on('data', c => data += c); res.on('end', () => resolve({ status: res.statusCode, body: data && JSON.parse(data) })); }); req.on('error', reject); if (payload) req.write(payload); req.end(); }); }
test('consumption API grants draft/approval/reversal roles and keeps warehouse read-only', async () => {
  const db = new Database(':memory:'); db.pragma('foreign_keys=ON'); ensureCoreSchema(db);
  db.prepare("INSERT INTO orders (id,order_num,inventory_lifecycle_version) VALUES (1,'API-B3',2)").run(); db.prepare('INSERT INTO items (id,order_id,diameter,total_weight) VALUES (1,1,12,10)').run(); db.prepare("INSERT INTO material_requirements_v2 (id,requirement_uid,order_id,item_id,lifecycle_version,diameter,material_type,required_kg,need_by_source,status,source) VALUES (1,'api-b3',1,1,2,12,'coil',10,'unknown','open','manual')").run(); db.prepare("INSERT INTO raw_material (id,diameter,material_type,weight_received,verification_status,active) VALUES (1,12,'coil',10,'approved',1)").run(); allocation.confirmAllocationPlan(db, { material_requirement_id: 1, idempotency_key: 'api-plan', lines: [{ raw_material_id: 1, allocated_kg: 10 }] }); const allocationLineId = db.prepare('SELECT id FROM allocation_plan_lines_v2').get().id;
  const app = express(); app.use(express.json()); app.use((req, _res, next) => { req.auth = { role: req.headers['x-role'], sub: 1 }; next(); }); app.use('/api', createRouter({ db, requireAnyRole })); const server = await new Promise(resolve => { const value=app.listen(0, () => resolve(value)); }); const port=server.address().port;
  try { const body={ material_requirement_id: 1, lines: [{ allocation_plan_line_id: allocationLineId, raw_material_id: 1, consumed_kg: 5 }] }; const warehouse = await request(port,'POST','/api/material-consumption-reports','warehouse',body); assert.equal(warehouse.status,403); const draft = await request(port,'POST','/api/material-consumption-reports','production',body); assert.equal(draft.status,201); const read = await request(port,'GET',`/api/material-consumption-reports/${draft.body.id}`,'warehouse'); assert.equal(read.status,200); const planner = await request(port,'POST',`/api/material-consumption-reports/${draft.body.id}/approve`,'production_planner',{idempotency_key:'approve'}); assert.equal(planner.status,200); const operatorReverse = await request(port,'POST',`/api/material-consumption-events/${planner.body.id}/reverse`,'production',{idempotency_key:'no',lines:[]}); assert.equal(operatorReverse.status,403); const managerReverse = await request(port,'POST',`/api/material-consumption-events/${planner.body.id}/reverse`,'manager',{idempotency_key:'yes',lines:[{original_event_line_id:planner.body.lines[0].id,raw_material_id:1,consumed_kg:5}]}); assert.equal(managerReverse.status,200); } finally { await new Promise(resolve => server.close(resolve)); db.close(); }
});
